export const files: Record<string, string> = {
  'index.html': '<!doctype html>\n<html lang="zh-CN">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1">\n  <title>Fieldnotes · 灵感记录</title>\n  <link rel="stylesheet" href="style.css">\n</head>\n<body>\n  <header><strong>fieldnotes.</strong><span>给日常，留一点空白</span></header>\n  <main>\n    <div class="eyebrow">A LITTLE SPACE FOR YOUR IDEAS</div>\n    <h1>好想法，<br>值得被留下。</h1>\n    <p>捕捉一闪而过的灵感，<br>让微小的念头，慢慢长成作品。</p>\n    <button id="record">记录今天的灵感 ↗</button>\n    <div class="notes"><article><small>01 / 灵感碎片</small><h2>让事情变简单，<br>本身就是一种创造。</h2><span>留给未来的自己</span></article><div class="circle"></div></div>\n  </main>\n  <footer>ONE THOUGHT AT A TIME.<span>慢一点，也没关系。</span></footer>\n  <script src="app.js"><\/script>\n</body>\n</html>',
  'style.css': '* { box-sizing: border-box; }\nbody { margin: 0; background: #f7f5ef; color: #34392c; font-family: system-ui, sans-serif; }\nheader { display:flex; justify-content:space-between; padding:28px; align-items:center; }\nheader strong { font-family:Georgia,serif; font-size:24px; letter-spacing:-1px; }\nheader span { font-size:10px; color:#848578; }\nmain { padding:38px 36px 22px; position:relative; overflow:hidden; }\n.eyebrow { font-size:8px; letter-spacing:2px; color:#8b8b78; }\nh1 { font-family:Georgia,"Songti SC",serif; font-size:clamp(34px,8vw,54px); font-weight:400; line-height:1.35; letter-spacing:-1px; margin:24px 0 16px; }\np { font-size:12px; line-height:1.9; color:#828573; }\nbutton { color:#f7f5ef; background:#444f3d; border:0; border-radius:6px; padding:13px 19px; margin-top:14px; cursor:pointer; font-size:11px; }\n.notes { margin:46px 0 20px; position:relative; padding:10px 0 15px; }\narticle { width:240px; padding:24px; background:#ebe5d8; transform:rotate(-4deg); position:relative; z-index:1; border-radius:2px; box-shadow:0 12px 20px #55502f0b; }\narticle small { font-size:8px; color:#939080; }\narticle h2 { font-family:Georgia,"Songti SC",serif; font-size:20px; font-weight:400; line-height:1.65; }\narticle span { font-size:8px; color:#94907d; }\n.circle { position:absolute; width:140px; height:140px; border:1px solid #acb496; border-radius:50%; top:0; right:5px; }\nfooter { display:flex; justify-content:space-between; border-top:1px solid #e8e4d9; padding:22px 28px; font-size:8px; color:#929481; letter-spacing:1px; }',
  'app.js': 'const button = document.querySelector("#record");\nbutton.addEventListener("click", () => {\n  button.textContent = "今天的一小步，已记录 ✓";\n});\n',
  'package.json': '{\n  "name": "fieldnotes",\n  "private": true,\n  "scripts": {\n    "dev": "vite",\n    "test": "demo-test"\n  }\n}\n',
  'src/main.ts': 'const record = document.querySelector<HTMLButtonElement>("#record");\n\nexport function bindRecorder(onRecord: () => void) {\n  record?.addEventListener("click", () => {\n    onRecord();\n  });\n}\n',
  'input/brief.md': '# 需求摘要\n\n- 记录今天的一条灵感\n- 不使用外部依赖\n',
  'output/report.html': "<!doctype html>\n<html lang='zh-CN'><head><meta charset='UTF-8'><title>验收报告</title></head><body><h1>验收通过</h1><p>input 与 output 属于会话暂存目录，不在代码树中显示。</p></body></html>",
  'notes/README.md': '# Fieldnotes\n\n一个使用 HTML、CSS 和 JavaScript 的独立网页。\n\n- 点击记录按钮验证交互\n- 无外部依赖\n- 示例测试命令 `demo-test` 成功，`demo-fail` 失败\n',
}
